### PR TITLE
Several r2dbc fixes for starter

### LINKED ISSUE #1588: Project with r2dbc and migration doesn't perform migration
If you create a project with r2dbc (or data-r2dbc) and a migration (eg: flyway), the migration is not performed

It requires datasource configuration and the hikari module for it to work.

### PR DESCRIPTION
**Pull request by timyates**
### R2dbc with TestContainers and a Migration didn't work as we end up with 2 datasources.

I added a Validator to stop this combination

### R2dbc with Test containers requires extra dependencies

If you use R2dbc with TestContainers, you also need to pull in the db lib from testcontainers and the jdbc-driver for that db.

See https://www.testcontainers.org/modules/databases/r2dbc/

### Migration requires a pool

If you select r2dbc and flyway (for example), you don't get a connection pool, so you don't get a datasource that the migration can use, so you get no migration.

This PR fixes that

Closes #1588

### CODE REVIEW

**Comment by timyates** [comment]
Used the jar this produced to run through

https://guides.micronaut.io/latest/micronaut-data-r2dbc-repository-gradle-java.html

And it worked as expected

File: starter-core/src/main/java/io/micronaut/starter/feature/database/r2dbc/R2dbcFeatureValidator.java [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+
+    @Override
+    public void validatePostProcessing(Options options, ApplicationType applicationType, Set<Feature> features) {
+        if (containsR2dbcFeature(features) && hasMigrationFeature(features) && hasTestContainersFeature(features)) {
+            throw new IllegalArgumentException("Testcontainers is not supported with R2DBC and Migration. Please remove the TestContainers feature to use Test Resources instead.");
+        }
+    }
+
+    private static boolean hasTestContainersFeature(Set<Feature> features) {
+        return features.stream().anyMatch(TestContainers.class::isInstance);
```
Comment (sdelamo) [inline starter-core/src/main/java/io/micronaut/starter/feature/database/r2dbc/R2dbcFeatureValidator.java]: could we extract a method `boolean hasFeature(Set<Features> features, Class featureClass)`

File: starter-core/src/test/groovy/io/micronaut/starter/build/gradle/GradleBuildTestVerifier.groovy [hunk 2]
```diff
@@ -52,7 +52,7 @@ class GradleBuildTestVerifier implements BuildTestVerifier {
 
     @Override
     boolean hasTestResourceDependency(String groupId, String artifactId) {
-        throw new UnsupportedOperationException("not yet implemented");
+        hasDependency(groupId, artifactId, "testResourcesService")
```
Comment (sdelamo) [inline starter-core/src/test/groovy/io/micronaut/starter/build/gradle/GradleBuildTestVerifier.groovy]: should we add this scope to `GradleConfiguration`?

File: starter-core/src/test/groovy/io/micronaut/starter/feature/database/r2dbc/DataR2dbcSpec.groovy [hunk 3]
```diff
@@ -80,6 +92,39 @@ class DataR2dbcSpec extends ApplicationContextSpec implements CommandOutputFixtu
...
+        when:
+        def feature = beanContext.getBean(db)
+        String template = new BuildBuilder(beanContext, BuildTool.GRADLE)
+                .features([DataR2dbc.NAME, feature.name, TestContainers.NAME])
+                .render()
+        def jdbcDriver = renderDependency(feature.javaClientDependency.get().build())
+        def r2dbcDriver = renderDependency(feature.r2DbcDependency.get().build())
+
+        then:
+        jdbcFeature.name == 'jdbc-hikari'
```
Comment (sdelamo) [inline starter-core/src/test/groovy/io/micronaut/starter/feature/database/r2dbc/DataR2dbcSpec.groovy:107]: please use the `BuildTestVerifier` API ?

File: starter-core/src/test/groovy/io/micronaut/starter/feature/database/r2dbc/DataR2dbcSpec.groovy [hunk 4]
```diff
@@ -128,12 +173,35 @@ class DataR2dbcSpec extends ApplicationContextSpec implements CommandOutputFixtu
...
+        def feature = beanContext.getBean(db)
+        String template = new BuildBuilder(beanContext, BuildTool.GRADLE)
+                .features(["data-r2dbc", feature.name, "flyway"])
+                .render()
+        def jdbcDriverDependency = feature.javaClientDependency.get().build()
+        def r2dbcDriverDependency = feature.r2DbcDependency.get().build()
+
+        then:
+        jdbcFeature.name == 'jdbc-hikari'
+        template.contains("annotationProcessor(\"io.micronaut.data:micronaut-data-processor\")")
```
Comment (sdelamo) [inline starter-core/src/test/groovy/io/micronaut/starter/feature/database/r2dbc/DataR2dbcSpec.groovy]: Please, use the `BuildVerifierAPI`

**Review by sdelamo — CHANGES_REQUESTED** [review]

File: starter-core/src/test/groovy/io/micronaut/starter/build/gradle/GradleBuildTestVerifier.groovy (hunk 2 above)
Comment (timyates) [reply starter-core/src/test/groovy/io/micronaut/starter/build/gradle/GradleBuildTestVerifier.groovy]: It's already there, no?

https://github.com/micronaut-projects/micronaut-starter/blob/551a2f618b308512159b11a83a9de141019f0c3f/starter-core/src/main/java/io/micronaut/starter/build/gradle/GradleConfiguration.java#L42

File: starter-core/src/main/java/io/micronaut/starter/feature/database/r2dbc/R2dbcFeatureValidator.java (hunk 1 above)
Comment (timyates) [reply starter-core/src/main/java/io/micronaut/starter/feature/database/r2dbc/R2dbcFeatureValidator.java]: Done in next push

File: starter-core/src/main/java/io/micronaut/starter/feature/database/r2dbc/R2dbc.java [hunk 5]
```diff
@@ -46,9 +50,11 @@ public class R2dbc implements R2dbcFeature {
     private static final String PASSWORD_KEY = PREFIX + "password";
 
     private final DatabaseDriverFeature defaultDbFeature;
+    private final Hikari hikari;
 
-    public R2dbc(DatabaseDriverFeature defaultDbFeature) {
+    public R2dbc(DatabaseDriverFeature defaultDbFeature, Hikari hikari) {
```
Comment (sdelamo) [inline starter-core/src/main/java/io/micronaut/starter/feature/database/r2dbc/R2dbc.java:62]: This is a breaking change. Can you annotate the new constructor with `@Inject` and keep the old one with `@Deprecated(forRemoval=True)`

**Review by sdelamo — CHANGES_REQUESTED** [review]

File: starter-core/src/main/java/io/micronaut/starter/feature/database/r2dbc/R2dbc.java (hunk 5 above)
Comment (sdelamo) [reply starter-core/src/main/java/io/micronaut/starter/feature/database/r2dbc/R2dbc.java:62]: ping @timyates

Comment (timyates) [reply starter-core/src/main/java/io/micronaut/starter/feature/database/r2dbc/R2dbc.java:62]: @sdelamo done!

Couldn't use `forRemoval` as thats a Java9 feature

Comment (sdelamo) [reply starter-core/src/main/java/io/micronaut/starter/feature/database/r2dbc/R2dbc.java:62]: > Couldn't use forRemoval as thats a Java9 feature

👍🏻

**Review by sdelamo — APPROVED** [review]
