### PR TITLE
Micrometer features need r2dbc-pool runtime dependency when combined with r2dbc feature

### LINKED ISSUE #1535: r2dbc-pool not available to be selected at project creation, but wanted by micrometer
### Description

Launch does not provide an option to select R2DBC-Pool to be included in a project. 

Also, if the users selects r2dbc and also metrics, the generated application does not run, as `micronaut-micrometer-core`
expects `io.r2dbc.pool.ConnectionPool` to be available in runtime . 

### Task List

- [X] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [X ] Full description of the issue provided (see below)

### Steps to Reproduce

1. On launch, select `data-r2dbc`, `postgres` and `micrometer-prometheus`
2. try to run the generated application

### Expected Behaviour

Application should start without errors

### Actual Behaviour

Application crashes with runtime error

### Environment Information

- **Operating System**: MacOS
- **Micronaut Version:** 3.7.3
- **JDK Version:** coreto-11

### PR DESCRIPTION
**Pull request by wetted**
fixes #1535

### CODE REVIEW

File: starter-core/src/main/java/io/micronaut/starter/feature/micrometer/Core.java [hunk 1]
```diff
@@ -20,10 +20,22 @@
 import io.micronaut.starter.build.dependencies.Dependency;
 import io.micronaut.starter.feature.Feature;
 
+import io.micronaut.starter.feature.database.r2dbc.R2dbcFeature;
 import jakarta.inject.Singleton;
 
 @Singleton
 public class Core implements Feature {
+    private static final Dependency MICRONAUT_MICROMETER_CORE = Dependency.builder()
+            .groupId("io.micronaut.micrometer")
```
Comment (sdelamo) [inline starter-core/src/main/java/io/micronaut/starter/feature/micrometer/Core.java:29]: This should use Micronaut Dependency Utils

**Review by sdelamo — APPROVED** [review]
