### PR TITLE
Fix log4j2 feature generating incorrect log4j2 dependencies

### LINKED ISSUE #1560: `mn` generates incorrect log4j2 dependencies
### Description

`mn create-app -f log4j2 prj-dir` generates `build.gradle` (or `build.gradle.kts` with `-b gradle_kotlin`) with following log4j deps:

```
implementation("org.apache.logging.log4j:log4j-core:2.19.0")
runtimeOnly("org.apache.logging.log4j:log4j-api:2.19.0")
runtimeOnly("org.apache.logging.log4j:log4j-slf4j-impl:2.17.2")
```

`log4j-api` should be compile-time dependency, `log4j-core` -- runtime dependency.

Apache Log4j publishes BOM, so it could be used to align all log4j2 component versions.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Run `mn create-app -f log4j2 prj-dir`
2. Look at `prj-dir/build.gradle` `dependencies` block

### Expected Behaviour

Expected dependencies:

```
implementation(platform("org.apache.logging.log4j:log4j-bom:2.19.0"))
implementation("org.apache.logging.log4j:log4j-api")
runtimeOnly("org.apache.logging.log4j:log4j-core")
runtimeOnly("org.apache.logging.log4j:log4j-slf4j-impl") 
// * log4j-slf4j-impl for slf4j-api 1.7.x 
// * log4j-slf4j2-impl for slf4j-api 2.0.x
```

### Actual Behaviour

```
implementation("org.apache.logging.log4j:log4j-core:2.19.0")
runtimeOnly("org.apache.logging.log4j:log4j-api:2.19.0")
runtimeOnly("org.apache.logging.log4j:log4j-slf4j-impl:2.17.2")
```

### Environment Information

- **Operating System**: ArchLinux (`Linux unterwelt 6.0.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 03 Nov 2022 18:01:58 +0000 x86_64 GNU/Linux`), KDE/Plasma
- **Micronaut Version:** `3.7.4`
- **JDK Version:** `OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8)`

### Example Application

See *Steps to Reproduce*

### PR DESCRIPTION
**Pull request by wetted**
closes #1560

### CODE REVIEW

File: starter-core/src/test/groovy/io/micronaut/starter/feature/logging/Log4j2Spec.groovy [hunk 1]
```diff
@@ -15,9 +15,10 @@ class Log4j2Spec extends ApplicationContextSpec {
                 .render()
 
         then:
-        template.contains('implementation("org.apache.logging.log4j:log4j-core')
-        template.contains('runtimeOnly("org.apache.logging.log4j:log4j-api')
-        template.contains('runtimeOnly("org.apache.logging.log4j:log4j-slf4j-impl')
+        template.contains('implementation platform("org.apache.logging.log4j:log4j-bom:')
```
Comment (sdelamo) [inline starter-core/src/test/groovy/io/micronaut/starter/feature/logging/Log4j2Spec.groovy]: Please, use `BuildTestVerifier`API

File: starter-core/src/test/groovy/io/micronaut/starter/feature/logging/Log4j2Spec.groovy [hunk 2]
```diff
@@ -15,9 +15,10 @@ class Log4j2Spec extends ApplicationContextSpec {
...
+        template.contains('implementation("org.apache.logging.log4j:log4j-api")')
+        template.contains('runtimeOnly("org.apache.logging.log4j:log4j-core")')
+        template.contains('runtimeOnly("org.apache.logging.log4j:log4j-slf4j-impl")')
     }
 
     void "org.apache.logging.log4j dependencies are present for log4j2 feature and build maven"() {
```
Comment (sdelamo) [inline starter-core/src/test/groovy/io/micronaut/starter/feature/logging/Log4j2Spec.groovy]: can you use the maven in the previous test as well and get rid of this test?

**Review by sdelamo — CHANGES_REQUESTED** [review]
This is a bug fix. right? Can you change the base to 3.8.x

**Review by sdelamo — APPROVED** [review]

**Review by timyates — APPROVED** [review]
