### PR TITLE
fix: command line app generation without test framework flag

### LINKED ISSUE #1473: Cli Unable to create kotlin-maven project [JDK17]
java version:
```
root@pc:java -version

java version "17.0.4.1" 2022-08-18 LTS
Java(TM) SE Runtime Environment (build 17.0.4.1+1-LTS-2)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.4.1+1-LTS-2, mixed mode, sharing)
```
cli version:
```
root@pc:mn --version
Micronaut Version: 3.7.1
```
error:
```
root@pc:mn create-app mn-kotlin --build=maven --lang=kotlin
| Error Cannot invoke "io.micronaut.starter.options.TestFramework.isKotlinTestFramework()" because the return value of "io.micronaut.starter.options.Options.getTestFramework()" is null

```

### PR DESCRIPTION
**Pull request by sdelamo**
Close https://github.com/micronaut-projects/micronaut-starter/issues/1473

### CODE REVIEW

**Comment by timyates** [comment]
@sdelamo is this a fix for https://github.com/micronaut-projects/micronaut-starter/issues/1473 ?

File: starter-core/src/test/groovy/io/micronaut/starter/application/ContextFactorySpec.groovy [hunk 1]
```diff
@@ -0,0 +1,39 @@
+package io.micronaut.starter.application
```
Comment (timyates) [inline starter-core/src/test/groovy/io/micronaut/starter/application/ContextFactorySpec.groovy:1]: This test passes without overriding `getOrder` in the Mockk feature, and without the comparator in `ContextFactory`...

Why do we need to handle the order?

File: starter-core/src/main/java/io/micronaut/starter/feature/test/Mockk.java [hunk 2]
```diff
@@ -73,9 +76,30 @@ public boolean isVisible() {
...
+                                .filter(LanguageFeature.class::isInstance)
+                                .anyMatch(f -> ((LanguageFeature) f).isKotlin())
+
+        ) && (
+                options.getTestFramework() != null ?
+                        options.getTestFramework().isKotlinTestFramework() :
+                        selectedFeatures.stream()
+                                .filter(TestFeature.class::isInstance)
+                                .anyMatch(f -> ((TestFeature) f).isKotlinTestFramework()));
+    }
```
Comment (timyates) [inline starter-core/src/main/java/io/micronaut/starter/feature/test/Mockk.java]: We *could* do this, but it's down to opinion if it's more readable... 🤔 

```suggestion
        return isValid(selectedFeatures, options::getBuildTool, t -> t == BuildTool.MAVEN, BuildFeature.class, BuildFeature::isMaven)
                && isValid(selectedFeatures, options::getLanguage, t -> t == Language.KOTLIN, LanguageFeature.class, LanguageFeature::isKotlin)
                && isValid(selectedFeatures, options::getTestFramework, t -> t.isKotlinTestFramework(), TestFeature.class, TestFeature::isKotlinTestFramework);
    }

    private <T, U extends Feature> boolean isValid(Set<Feature> selectedFeatures, Supplier<T> supplier, Predicate<T> nonNull, Class<U> nullFeature, Predicate<U> nullFeatureTest) {
        T suppliedValue = supplier.get();
        return suppliedValue != null 
                ? nonNull.test(suppliedValue)
                : selectedFeatures.stream().filter(nullFeature::isInstance).map(nullFeature::cast).anyMatch(nullFeatureTest);
    }
```

File: starter-core/src/test/groovy/io/micronaut/starter/application/ContextFactorySpec.groovy (hunk 1 above)
Comment (sdelamo) [reply starter-core/src/test/groovy/io/micronaut/starter/application/ContextFactorySpec.groovy:1]: Currently, we default to Junit for Kotlin. Because of that, it passes without the order. 

Today, if we changed the default for Kotlin and set it to KoTest, Mockk is not automatically applied. 

I have added a test that verifies that test features are applied before features that depend on them being present.

I added a test: 

https://github.com/micronaut-projects/micronaut-starter/pull/1482/commits/0d3505acdde3c6a25affaab7a68743fcb723de08

**Comment by sdelamo** [comment]
> @sdelamo is this a fix for #1473 ?

Yes

**Comment by timyates** [comment]
This causes some test failures https://ge.micronaut.io/s/lfnn6grpe7emo/tests/overview?outcome=failed

**Comment by sdelamo** [comment]
> This causes some test failures https://ge.micronaut.io/s/lfnn6grpe7emo/tests/overview?outcome=failed

bean pollution. I used by mistake @Property instead of Requires

**Review by timyates — APPROVED** [review]
