### PR TITLE
@MicronautTest(transactional = false) for data-mongodb-reactive and data-r2dbc

### LINKED ISSUE #1455: Test fails for application generated with data-mongodb-reactive
If you generate an app with data-mongodb-reactive

https://micronaut.io/launch?type=DEFAULT&name=demo&package=com.example&javaVersion=JDK_11&lang=JAVA&build=GRADLE&test=JUNIT&features=data-mongodb-reactive&version=3.7.0

and run tests it fails: 

io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.transaction.test.DefaultTestTransactionExecutionListener]

Message: Transaction mode is not supported when the synchronous transaction manager is created using Reactive transaction manager!

### PR DESCRIPTION
**Pull request by sdelamo**
Close https://github.com/micronaut-projects/micronaut-starter/issues/1455

### CODE REVIEW

**Comment by sdelamo** [comment]
A heads-up. I talked with @dstepanov before 3.7.0 

> I am getting an error in the data mongodb async guide: "Message: Transaction mode is not supported when the synchronous transaction manager is created using Reactive transaction manager!". Is this something fixed/changd in the version of data released yesterday

> @dstepanov 
You might need to disable transactions for the tests

> @sdelamo 
is this a breaking change introduce in 3.7 ? I think this was not present yesterday. using @MicronautTest(transactional=false) instead of @MicronautTest works

> @dstepanov 
That's actually the correct behavior to let user know there is no transaction for the reactive stuff

https://github.com/micronaut-projects/micronaut-guides/pull/1078/commits/4e6ae5ba245a1813764969bda6e3c128a2a3fc2e

File: starter-core/src/main/java/io/micronaut/starter/feature/database/TransactionalNotSupported.java [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+package io.micronaut.starter.feature.database;
+
+/**
+ * Market interface for features which don't support transactional.
```
Comment (timyates) [inline starter-core/src/main/java/io/micronaut/starter/feature/database/TransactionalNotSupported.java]:
```suggestion
 * Marker interface for features which don't support transactional.
```

**Review by timyates — APPROVED** [review]
