### PR TITLE
Merge and reconcile BuildTestVerifier API with changes/improvements from 3.10.x and 4.2.x.

### LINKED ISSUE #2165: Merge and reconcile BuiltTestVerifier API from 3.10.x and 4.2.x branches
1. BuildTestVerifier on 4.2.x branch doesn't work for Kotlin with Gradle (and we have no tests that use the combination for `hasDependency`, etc.
2. there are fixes/enhancements on both 3.10.x and 4.2.x branches and some are in conflict.

We should reconcile the improvements in 3.10x in 4.2.x. The hasDependency/hasAnnotationProcessor API should work with all combinations of language and build tool.

### PR DESCRIPTION
**Pull request by wetted**
see #2074

Note: using BuildTestVerifier was broken for tests with Kotlin and Gradle, but we weren't testing for that anywhere (I have tests in 3.10.x that do). Now it works.

fixes #2165

### CODE REVIEW

File: starter-core/src/test/groovy/io/micronaut/starter/feature/spring/SpringDataJdbcSpec.groovy [hunk 1]
```diff
@@ -53,118 +55,21 @@ class SpringDataJdbcSpec extends ApplicationContextSpec {
     }
 
     @Unroll
-    void 'test spring-data-jdbc with Gradle for language=#language'() {
+    void 'test spring-data-jdbc with buildTool=#buildTool for language=#language'(Language language, BuildTool buildTool) {
         when:
-        String template = new BuildBuilder(beanContext, BuildTool.GRADLE)
-                .features(['spring-data-jdbc', 'kapt'])
+        String template = new BuildBuilder(beanContext, buildTool)
+                .features(['spring-data-jdbc', buildTool == BuildTool.MAVEN ? 'kapt' : 'ksp'])
```
Comment (timyates) [inline starter-core/src/test/groovy/io/micronaut/starter/feature/spring/SpringDataJdbcSpec.groovy]: These (kapt, ksp) are the defaults... why are we adding them in?

File: starter-core/src/test/groovy/io/micronaut/starter/feature/validator/MicronautValidationFeatureSpec.groovy [hunk 2]
```diff
@@ -80,12 +80,12 @@ class MicronautValidationFeatureSpec extends ApplicationContextSpec implements C
         String template = new BuildBuilder(beanContext, buildTool)
                 .applicationType(ApplicationType.FUNCTION)
                 .language(language)
-                .features(['validation', 'kapt'])
+                .features(['validation', buildTool == BuildTool.MAVEN ? 'kapt' : 'ksp'])
```
Comment (timyates) [inline starter-core/src/test/groovy/io/micronaut/starter/feature/validator/MicronautValidationFeatureSpec.groovy]: These (kapt, ksp) are the defaults... why are we adding them in?

File: starter-core/src/test/groovy/io/micronaut/starter/feature/picocli/PicocliSpec.groovy [hunk 3]
```diff
@@ -22,7 +22,7 @@ class PicocliSpec extends ApplicationContextSpec {
         String template = new BuildBuilder(beanContext, BuildTool.GRADLE)
                 .language(language)
                 .applicationType(ApplicationType.CLI)
-                .features(['kapt'])
+                .features(['ksp'])
```
Comment (timyates) [inline starter-core/src/test/groovy/io/micronaut/starter/feature/picocli/PicocliSpec.groovy]: This is the default, if we're going to switch from using Kapt, we don't need to provide `ksp`, just remove this line

File: starter-core/src/test/groovy/io/micronaut/starter/feature/picocli/PicocliSpec.groovy [hunk 4]
```diff
@@ -22,7 +22,7 @@ class PicocliSpec extends ApplicationContextSpec {
...
                 .render()
 
         then:
```
Comment (timyates) [inline starter-core/src/test/groovy/io/micronaut/starter/feature/picocli/PicocliSpec.groovy:28]: Should we switch to use the BuildVerifier here?

File: starter-core/src/test/groovy/io/micronaut/starter/feature/other/OpenApiSpec.groovy [hunk 5]
```diff
@@ -34,18 +34,13 @@ class OpenApiSpec extends ApplicationContextSpec  implements CommandOutputFixtur
     void 'test swagger with #buildTool for language=#language'(Language language, BuildTool buildTool) {
         when:
         String template = new BuildBuilder(beanContext, buildTool)
-                .features(['openapi', 'kapt'])
+                .features(['openapi', buildTool == BuildTool.MAVEN ? 'kapt' : 'ksp'])
```
Comment (timyates) [inline starter-core/src/test/groovy/io/micronaut/starter/feature/other/OpenApiSpec.groovy]: These (kapt, ksp) are the defaults... why are we adding them in?

File: starter-core/src/test/groovy/io/micronaut/starter/feature/aws/DynamoDbSpec.groovy [hunk 6]
```diff
@@ -29,7 +29,7 @@ class DynamoDbSpec extends ApplicationContextSpec implements CommandOutputFixtur
         when:
         String template = new BuildBuilder(beanContext, buildTool)
                 .language(language)
-                .features([DynamoDb.NAME, 'kapt'])
+                .features([DynamoDb.NAME, buildTool == BuildTool.MAVEN ? 'kapt' : 'ksp'])
```
Comment (timyates) [inline starter-core/src/test/groovy/io/micronaut/starter/feature/aws/DynamoDbSpec.groovy]: These (kapt, ksp) are the defaults... why are we adding them in?

File: starter-core/src/test/groovy/io/micronaut/starter/build/gradle/GradleBuildTestVerifier.groovy [hunk 7]
```diff
@@ -75,6 +86,14 @@ class GradleBuildTestVerifier implements BuildTestVerifier {
         })
     }
 
+    @Override
+    boolean hasExclusion(String groupId, String artifactId) {
+        // GRADLE: exclude(group: "io.micronaut.sql", module: "micronaut-hibernate-jpa")
+        // GRADLE_KOTLIN: exclude(group = "io.micronaut.sql", module = "micronaut-hibernate-jpa")
+        String pattern = /(?s).*exclude\(group\s?[:=]\s*"${groupId}", module\s?[:=]\s*"${artifactId}"\)\s*/
+        Pattern.compile(pattern).matcher(template).find()
```
Comment (timyates) [inline starter-core/src/test/groovy/io/micronaut/starter/build/gradle/GradleBuildTestVerifier.groovy]:
```suggestion
        template =~ /exclude\(group\s?[:=]\s?"${groupId}", module\s?[:=]\s?"${artifactId}"\)/
```

**Review by timyates — CHANGES_REQUESTED** [review]

File: starter-core/src/test/groovy/io/micronaut/starter/feature/spring/SpringDataJdbcSpec.groovy (hunk 1 above)
Comment (wetted) [reply starter-core/src/test/groovy/io/micronaut/starter/feature/spring/SpringDataJdbcSpec.groovy]: yeah, you are right. I don't know why the 'kapt' was there to begin with and I added it months ago. 🤷‍♂️

File: starter-core/src/test/groovy/io/micronaut/starter/feature/spring/SpringDataJdbcSpec.groovy [hunk 8]
```diff
@@ -53,118 +55,21 @@ class SpringDataJdbcSpec extends ApplicationContextSpec {
...
-            <path>
-              <groupId>io.micronaut.spring</groupId>
-              <artifactId>micronaut-spring-annotation</artifactId>
-              <version>\${micronaut.spring.version}</version>
-              <exclusions>
-                <exclusion>
-                  <groupId>io.micronaut</groupId>
-                  <artifactId>micronaut-core</artifactId>
-                </exclusion>
-              </exclusions>
```
Comment (timyates) [inline starter-core/src/test/groovy/io/micronaut/starter/feature/spring/SpringDataJdbcSpec.groovy]: We used to test that this exclusion existed for Maven

We no longer seem to do that?

**Review by timyates — CHANGES_REQUESTED** [review]

File: starter-core/src/test/groovy/io/micronaut/starter/feature/spring/SpringDataJdbcSpec.groovy (hunk 8 above)
Comment (wetted) [reply starter-core/src/test/groovy/io/micronaut/starter/feature/spring/SpringDataJdbcSpec.groovy]: I will add that back.

Comment (wetted) [reply starter-core/src/test/groovy/io/micronaut/starter/feature/spring/SpringDataJdbcSpec.groovy]: ping @timyates this exposed an issue with the hasExclusions API (didn't work for Maven annotation processors). Now fixed.

File: starter-core/src/test/groovy/io/micronaut/starter/feature/aws/DynamoDbSpec.groovy [hunk 9]
```diff
@@ -51,15 +51,12 @@ class DynamoDbSpec extends ApplicationContextSpec implements CommandOutputFixtur
...
         BuildTestVerifier verifier = BuildTestUtil.verifier(buildTool, language, template)
 
         then:
         verifier.hasDependency("io.micronaut.aws", "micronaut-aws-sdk-v2", Scope.COMPILE)
-        template.contains("""    implementation("software.amazon.awssdk:dynamodb") {
-                            |      exclude(group$mapNotation "software.amazon.awssdk", module$mapNotation "apache-client")
-                            |      exclude(group$mapNotation "software.amazon.awssdk", module$mapNotation "netty-nio-client")
-                            |    }""".stripMargin())
+        verifier.hasExclusion("software.amazon.awssdk", "apache-client")
+        verifier.hasExclusion("software.amazon.awssdk", "netty-nio-client")
```
Comment (timyates) [inline starter-core/src/test/groovy/io/micronaut/starter/feature/aws/DynamoDbSpec.groovy]: Here again, this isn't testing the same thing...

I think the new hasExclusion method is missing the concept of _where_ it's excluded from

**Review by timyates — CHANGES_REQUESTED** [review]

**Comment by sdelamo** [comment]
@timyates please, review this.

File: starter-core/src/test/groovy/io/micronaut/starter/build/BuildTestVerifier.groovy [hunk 10]
```diff
@@ -1,12 +1,17 @@
...
+import io.micronaut.starter.build.dependencies.Scope
 
 /**
  * You can get an instance via {@link io.micronaut.starter.build.BuildTestUtil}.
  */
 interface BuildTestVerifier {
 
+    boolean hasAnnotationProcessor(String groupId, String artifactId)
+
+    boolean hasAnnotationProcessor(String groupId, String artifactId, boolean isTest)
```
Comment (sdelamo) [inline starter-core/src/test/groovy/io/micronaut/starter/build/BuildTestVerifier.groovy]: Please, remove the boolean 
```suggestion
    boolean hasTestAnnotationProcessor(String groupId, String artifactId)
```

File: starter-core/src/test/groovy/io/micronaut/starter/build/gradle/GradleBuildTestVerifier.groovy [hunk 11]
```diff
@@ -18,6 +19,16 @@ class GradleBuildTestVerifier implements BuildTestVerifier {
         this.testFramework = testFramework
     }
 
+    @Override
+    boolean hasAnnotationProcessor(String groupId, String artifactId) {
+        hasDependency(groupId, artifactId, Scope.ANNOTATION_PROCESSOR)
+    }
+
+    @Override
+    boolean hasAnnotationProcessor(String groupId, String artifactId, boolean isTest) {
```
Comment (sdelamo) [inline starter-core/src/test/groovy/io/micronaut/starter/build/gradle/GradleBuildTestVerifier.groovy]:
```suggestion
 boolean hasTestAnnotationProcessor(String groupId, String artifactId)
```

File: starter-core/src/test/groovy/io/micronaut/starter/build/maven/MavenBuildTestVerifier.groovy [hunk 12]
```diff
@@ -18,8 +18,27 @@ class MavenBuildTestVerifier implements BuildTestVerifier {
...
+    boolean hasAnnotationProcessor(String groupId, String artifactId) {
+        if (language == Language.GROOVY) {
+            return hasDependency(groupId, artifactId, Scope.ANNOTATION_PROCESSOR)
+        } else {
+            return hasAnnotationProcessor(groupId, artifactId, Scope.ANNOTATION_PROCESSOR)
+        }
+    }
+
+    @Override
+    boolean hasAnnotationProcessor(String groupId, String artifactId, boolean isTest) {
```
Comment (sdelamo) [inline starter-core/src/test/groovy/io/micronaut/starter/build/maven/MavenBuildTestVerifier.groovy]:
```suggestion
 boolean hasTestAnnotationProcessor(String groupId, String artifactId)
```

File: starter-core/src/test/groovy/io/micronaut/starter/build/maven/MavenBuildTestVerifier.groovy [hunk 13]
```diff
@@ -18,8 +18,27 @@ class MavenBuildTestVerifier implements BuildTestVerifier {
         this.language = language
     }
 
+    @Override
+    boolean hasAnnotationProcessor(String groupId, String artifactId) {
+        if (language == Language.GROOVY) {
```
Comment (sdelamo) [inline starter-core/src/test/groovy/io/micronaut/starter/build/maven/MavenBuildTestVerifier.groovy]: replace the method content with : 

` return hasAnnotationProcessor(groupId, artifactId, Scope.ANNOTATION_PROCESSOR);`

File: starter-core/src/test/groovy/io/micronaut/starter/build/maven/MavenBuildTestVerifier.groovy [hunk 14]
```diff
@@ -18,8 +18,27 @@ class MavenBuildTestVerifier implements BuildTestVerifier {
...
+            return hasDependency(groupId, artifactId, Scope.ANNOTATION_PROCESSOR)
+        } else {
+            return hasAnnotationProcessor(groupId, artifactId, Scope.ANNOTATION_PROCESSOR)
+        }
+    }
+
+    @Override
+    boolean hasAnnotationProcessor(String groupId, String artifactId, boolean isTest) {
+        Scope scope = isTest ? Scope.TEST_ANNOTATION_PROCESSOR : Scope.ANNOTATION_PROCESSOR
```
Comment (sdelamo) [inline starter-core/src/test/groovy/io/micronaut/starter/build/maven/MavenBuildTestVerifier.groovy]: replace method content with ` return hasAnnotationProcessor(groupId, artifactId, Scope.TEST_ANNOTATION_PROCESSOR);`

**Review by sdelamo — CHANGES_REQUESTED** [review]

**Review by timyates — APPROVED** [review]

File: starter-core/src/test/groovy/io/micronaut/starter/build/maven/MavenBuildTestVerifier.groovy (hunk 14 above)
Comment (sdelamo) [reply starter-core/src/test/groovy/io/micronaut/starter/build/maven/MavenBuildTestVerifier.groovy]: see: https://github.com/micronaut-projects/micronaut-starter/pull/2162/commits/ff4714f83e4e9c55413efc8f53d1dd92f4fe9eb2

File: starter-core/src/test/groovy/io/micronaut/starter/build/maven/MavenBuildTestVerifier.groovy (hunk 13 above)
Comment (sdelamo) [reply starter-core/src/test/groovy/io/micronaut/starter/build/maven/MavenBuildTestVerifier.groovy]: see https://github.com/micronaut-projects/micronaut-starter/pull/2162/commits/ff4714f83e4e9c55413efc8f53d1dd92f4fe9eb2

File: starter-core/src/test/groovy/io/micronaut/starter/build/maven/MavenBuildTestVerifier.groovy (hunk 12 above)
Comment (sdelamo) [reply starter-core/src/test/groovy/io/micronaut/starter/build/maven/MavenBuildTestVerifier.groovy]: see https://github.com/micronaut-projects/micronaut-starter/pull/2162/commits/ff4714f83e4e9c55413efc8f53d1dd92f4fe9eb2

File: starter-core/src/test/groovy/io/micronaut/starter/build/gradle/GradleBuildTestVerifier.groovy (hunk 11 above)
Comment (sdelamo) [reply starter-core/src/test/groovy/io/micronaut/starter/build/gradle/GradleBuildTestVerifier.groovy]: see https://github.com/micronaut-projects/micronaut-starter/pull/2162/commits/ff4714f83e4e9c55413efc8f53d1dd92f4fe9eb2

File: starter-core/src/test/groovy/io/micronaut/starter/build/BuildTestVerifier.groovy (hunk 10 above)
Comment (sdelamo) [reply starter-core/src/test/groovy/io/micronaut/starter/build/BuildTestVerifier.groovy]: see https://github.com/micronaut-projects/micronaut-starter/pull/2162/commits/ff4714f83e4e9c55413efc8f53d1dd92f4fe9eb2
