### PR TITLE
Switch to enable classpathInference for test resources

### LINKED ISSUE #1522: Mysql Maven project doesn't work out of the box with TestResources
If you create a maven app with the mysql feature, the mysql driver doesn't end up on the classpath of the test-resources

```
Caused by: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at org.testcontainers.containers.JdbcDatabaseContainer.getJdbcDriverInstance(JdbcDatabaseContainer.java:200)
        ... 83 common frames omitted
```

The workaround is to change the maven plugin config from

```
          <configuration>
            <classpathInference>false</classpathInference>
```

To

```
          <configuration>
            <classpathInference>true</classpathInference>
```

@alvarosanchez should we be setting this to `true` by default for everything using test-resources?

Micronaut 3.7.3

### PR DESCRIPTION
**Pull request by timyates**
It was noticed in #1522 that a plain mysql app didn't work as the TR service didn't have the driver class available.

We decided to enable classpathInference as that works, and that is how the Gradle plugin works also

### CODE REVIEW

**Review by alvarosanchez — CHANGES_REQUESTED** [review]
`classpathInference` defaults to true, so simply remove the tag.

Also, `testResourcesDependencies` is only to be used when NOT using classpath inference.

**Comment by timyates** [comment]
> Also, `testResourcesDependencies` is only to be used when NOT using classpath inference.

Is that true?  I thought we had to add the test-resources module to `testResourcesDependencies`, and if we're using reactive sql we need to add the jdbc-driver too?

**Comment by alvarosanchez** [comment]
> Is that true? I thought we had to add the test-resources module to `testResourcesDependencies`, and if we're using reactive sql we need to add the jdbc-driver too?

We have probably been doing this wrong, as @melix [clarified](https://github.com/micronaut-projects/micronaut-starter/issues/1522#issuecomment-1310316056). `io.micronaut.testresources:micronaut-test-resources-jdbc-mysql` will definitely be inferred automatically.

**Comment by timyates** [comment]
> We have probably been doing this wrong, as @melix https://github.com/micronaut-projects/micronaut-starter/issues/1522#issuecomment-1310316056. io.micronaut.testresources:micronaut-test-resources-jdbc-mysql will definitely be inferred automatically.

But we still need to add the mysql driver if for example they are using the vertx reactive one in their code?

**Comment by alvarosanchez** [comment]
> But we still need to add the mysql driver if for example they are using the vertx reactive one in their code?

I guess so. But in your original comment you mentioned a plain mysql app. The `mysql` feature will add the driver to the classpath

**Comment by timyates** [comment]
Sorry, I was talking about https://github.com/micronaut-projects/micronaut-starter/pull/1528#issuecomment-1311893057

I'll take a look

**Comment by timyates** [comment]
@melix do we have a list of rules as to when the `micronaut-test-resources-@resourceName` module is required?

I'm trying to extract this from Rocker and into java

https://github.com/micronaut-projects/micronaut-starter/blob/dd21765c5d1441e1320af425ff7a36b3d2b52358/starter-core/src/main/java/io/micronaut/starter/feature/build/maven/templates/pom.rocker.raw#L181-L201

**Comment by timyates** [comment]
Found another issue...

If `TestContainers` is selected, it's supposed to disable `TestResources` 🤔

File: starter-core/src/main/java/io/micronaut/starter/feature/testresources/EaseTestingFeature.java [hunk 1]
```diff
@@ -36,7 +36,7 @@ protected EaseTestingFeature(TestContainers testContainers,
 
     @Override
     public void processSelectedFeatures(FeatureContext featureContext) {
-        if (!featureContext.isPresent(TestResources.class) && testResources != null) {
+        if (!featureContext.isPresent(TestContainers.class) && testResources != null) {
```
Comment (alvarosanchez) [inline starter-core/src/main/java/io/micronaut/starter/feature/testresources/EaseTestingFeature.java:39]: Are you sure this is correct? I think the original intent was to check the presence of `TestResources` before adding it. It's an idiom repeated all over starter.

Comment (timyates) [reply starter-core/src/main/java/io/micronaut/starter/feature/testresources/EaseTestingFeature.java:39]: The requirement is:

If they have selected `TestContainers` then don't apply `TestResources`

If they have selected nothing, apply `TestResources`

Previously we applied `TestResources` all the time, whether they had added `TestContainers` or not 🤔 

Do you have a link to the idiom?

**Review by alvarosanchez — APPROVED** [review]

**Review by sdelamo — APPROVED** [review]
