### PR TITLE
fix: oracle-cloud-atp fixes

### LINKED ISSUE #912: Adding the `oracle-cloud-atp` and data-jdbc modules includes h2 erroneously
### Description

Adding the `oracle-cloud-atp` and data-jdbc modules includes h2 erroneously

### Steps to Reproduce

1. `mn create-app demo --features oracle-cloud-atp --features data-jdbc`

### Expected Behaviour

Should not include h2 as oracle database is used

### Actual Behaviour

Sets the dialect in config to h2

### Environment Information

- **Operating System**: all
- **Micronaut Version:** 3.0.1
- **JDK Version:** all

### Example Application

N/A

### LINKED ISSUE #942: You can generate a JDK8 application with oracle-cloud-atp but guide tells user to use JDK11
Guide [ACCESS AN ORACLE AUTONOMOUS DATABASE](https://guides.micronaut.io/latest/micronaut-oracle-autonomous-db-gradle-java.html) tells users to use JDK 11 as mininum. However, we allow JDK 8 applications to be generated with `oracle-cloud-atp`

 @burtbeckwith could you review the oracle features and allow only compatible JDK versions?. See GCP features for an example of JDK11 or above compatible features.

### PR DESCRIPTION
**Pull request by pgressa**
Fixes #942 
Fixes #912

### CODE REVIEW

File: starter-core/src/main/java/io/micronaut/starter/feature/oraclecloud/OracleCloudAutonomousDatabase.java [hunk 1]
```diff
@@ -100,6 +106,8 @@ public void apply(GeneratorContext generatorContext) {
             cfg.remove(jdbc.getUrlKey());
             cfg.remove(jdbc.getUsernameKey());
             cfg.remove(jdbc.getPasswordKey());
+            removeDatasourceDefaultConfig("dialect", "H2", cfg);
+            removeDatasourceDefaultConfig("schema-generate", "CREATE_DROP", cfg);
```
Comment (jameskleeh) [inline starter-core/src/main/java/io/micronaut/starter/feature/oraclecloud/OracleCloudAutonomousDatabase.java]: Can you explain why this needs to be done?

Comment (pgressa) [reply starter-core/src/main/java/io/micronaut/starter/feature/oraclecloud/OracleCloudAutonomousDatabase.java]: Since it is not in memory database I think the users do not expect the schema always recreated. Also I think we should kinda be consistent with the guideline for atp https://guides.micronaut.io/latest/micronaut-oracle-autonomous-db-gradle-java.html.

**Review by graemerocher — APPROVED** [review]

**Comment by jameskleeh** [comment]
@pgressa Can you please review the last commits? I believe the end result is the same but its no longer possible to have atp with another database implementation and choosing atp will add a jdbc implementation if none is chosen

**Comment by pgressa** [comment]
@jameskleeh sure, but next time let me finish it, I had it in progress, but had to work on more priority stuff

File: starter-core/src/main/java/io/micronaut/starter/feature/oraclecloud/OracleCloudAutonomousDatabase.java [hunk 2]
```diff
@@ -78,33 +82,63 @@ public String getCategory() {
...
+        config.put("datasources.default.walletPassword", "");
+        return config;
+    }
+
     @Override
     public void apply(GeneratorContext generatorContext) {
         generatorContext.addDependency(Dependency.builder()
                 .compile()
-                .groupId("io.micronaut.oraclecloud").artifactId("micronaut-oraclecloud-atp")
+                .groupId("io.micronaut.oraclecloud")
```
Comment (pgressa) [inline starter-core/src/main/java/io/micronaut/starter/feature/oraclecloud/OracleCloudAutonomousDatabase.java]: the groupId could be externalised this into static property and used by OracleCloudSdk

File: starter-core/src/main/java/io/micronaut/starter/feature/oraclecloud/OracleCloudAutonomousDatabase.java [hunk 3]
```diff
@@ -13,26 +13,30 @@
...
+import java.util.Map;
+
 @Singleton
-public class Atp implements Feature {
+public class OracleCloudAutonomousDatabase extends DatabaseDriverFeature {
+
     private final OracleCloudSdk oracleCloudSdkFeature;
 
-    public Atp(OracleCloudSdk oracleCloudSdkFeature) {
+    public OracleCloudAutonomousDatabase(JdbcFeature jdbcFeature, TestContainers testContainers, OracleCloudSdk oracleCloudSdkFeature) {
```
Comment (pgressa) [inline starter-core/src/main/java/io/micronaut/starter/feature/oraclecloud/OracleCloudAutonomousDatabase.java:38]: Given the fact this will become DatabaseDriverFeature, we need to update the guide https://guides.micronaut.io/latest/micronaut-oracle-autonomous-db-gradle-java.html which uses `mn create-app --features=oracle,oracle-cloud-atp,data-jdbc,oracle-cloud-sdk,flyway,testcontainers example.micronaut.micronautguide --build=gradle --lang=java --jdk=11` to generate template, and it will fail since `oracle` and `oracle-cloud-atp` will be both db feature. Also we can remove `oracle-cloud-sdk`.

Comment (sdelamo) [reply starter-core/src/main/java/io/micronaut/starter/feature/oraclecloud/OracleCloudAutonomousDatabase.java:38]: @pgressa can you please create an issue in `micronaut-guides` and assign it to yourself?
